## 이미지 글 추출하기

In [1]:
!pip install pillow pytesseract

  Created wheel for pytesseract: filename=pytesseract-0.3.7-py2.py3-none-any.whl size=13953 sha256=1d7793c0fadf80f16e43b70c5178e0fbbc94d5f0d1f281316b9e9274afe37728
  Stored in directory: /root/.cache/pip/wheels/81/20/7e/1dd0daad1575d5260916bb1e9781246430647adaef4b3ca3b3
Successfully built pytesseract


In [2]:
!pip install -upgrade pip


Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: -u


In [4]:
from pytesseract import pytesseract
from PIL import Image

In [5]:
def load_image(path, mode=' '):
  return Image.opne(path)

In [6]:
# pytesseract 시작하는 함수
def run_pytesseract(image, path_engine, config='-l eng'):
  pytesseract.tesseract_cmd = path_engine
  result = pytesseract.image_to_string(imgae, config=config) # 이미지를 스트링으로
  return result

In [7]:
import pytesseract
import cv2
import os
from PIL import Image
from google.colab.patches import cv2_imshow

In [8]:
!pwd

/content


In [9]:
!sudo apt install tesseract-ocr
!pip install pytesseract

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  tesseract-ocr-eng tesseract-ocr-osd
The following NEW packages will be installed:
  tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd
0 upgraded, 3 newly installed, 0 to remove and 39 not upgraded.
Need to get 4,795 kB of archives.
After this operation, 15.8 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 tesseract-ocr-eng all 4.00~git24-0e00fe6-1.2 [1,588 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 tesseract-ocr-osd all 4.00~git24-0e00fe6-1.2 [2,989 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/universe amd64 tesseract-ocr amd64 4.00~git2288-10f4998a-2 [218 kB]
Fetched 4,795 kB in 2s (3,045 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl

In [12]:
image = cv2.imread('/content/drive/MyDrive/dataset/test.jpg')

In [13]:
print(image)

[[[ 76  92 109]
  [ 70  86 103]
  [ 77  93 109]
  ...
  [127 128 132]
  [131 132 136]
  [135 136 140]]

 [[ 79  95 112]
  [ 72  88 105]
  [ 78  94 110]
  ...
  [129 130 134]
  [131 132 136]
  [134 135 139]]

 [[ 80  96 113]
  [ 73  89 106]
  [ 77  93 109]
  ...
  [131 132 136]
  [131 132 136]
  [132 133 137]]

 ...

 [[ 49  75  89]
  [ 51  77  91]
  [ 52  78  92]
  ...
  [ 36  51  67]
  [ 40  55  71]
  [ 40  55  71]]

 [[ 51  77  91]
  [ 51  77  91]
  [ 52  78  92]
  ...
  [ 38  53  69]
  [ 41  56  72]
  [ 39  54  70]]

 [[ 53  79  93]
  [ 52  78  92]
  [ 51  77  91]
  ...
  [ 45  60  76]
  [ 48  63  79]
  [ 46  61  77]]]


In [14]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [18]:
filename = "{}.png".format(os.getpid())
cv2.imwrite(filename, gray)

True

In [19]:
# pytesseract의 image to string을 써주고, 숫자는 lang ="none"
text = pytesseract.image_to_string(Image.open(filename), lang=None)
os.remove(filename)

In [20]:
print(text)

 

Wwivri

aee

IGA 5G Wave2 2A1B

>> KT G

PW >> 8hg79eh832

        
 

OlSGnAMg!

Olu
fal

 



In [21]:
cv2_imshow(image)

Output hidden; open in https://colab.research.google.com to view.

## PDF에서 글 추출하기

In [22]:
!pip install pdfminer

     |████████████████████████████████| 4.2MB 8.0MB/s 
     |████████████████████████████████| 1.9MB 51.7MB/s 
  Created wheel for pdfminer: filename=pdfminer-20191125-cp37-none-any.whl size=6140096 sha256=989cac5d5952b07f4dcfa11c37e87036389a08b786e6ddf1c08a46954c23715c
  Stored in directory: /root/.cache/pip/wheels/e1/00/af/720a55d74ba3615bb4709a3ded6dd71dc5370a586a0ff6f326
Successfully built pdfminer


In [23]:
from io import StringIO
import pdfminer
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage

In [28]:
# pdf를 text로 변경하는 함수
def convert_pdf2txt(path):
  manager = PDFResourceManager()
  file_object = StringIO()
  converter = TextConverter(manager, file_object, laparams=LAParams())
  with open(path, 'rb') as f:
    interpreter = PDFPageInterpreter(manager, converter)
    for page in PDFPage.get_pages(f, maxpages=0, caching=True, check_extractable=True):
      interpreter.process_page(page)
  converter.close()
  text =file_object.getvalue()
  file_object.close()
  return text

In [30]:
convert_pdf2txt('/content/drive/MyDrive/dataset/sample_papers.pdf')

"지역사회간호학회지 제24권 제1호, 2013년 3월\nJ Korean Acad Community Health Nurs Vol. 24 No. 1, 1-10, March 2013\n\nISSN 1225-9594\nhttp://dx.doi.org/10.12799/jkachn.2013.24.1.1\n\n지역사회거주 노인의 황반변성 관련 요인\n\n김철규1·박윤경2·박승미3\n\n청주대학교 간호학과1, 한국실명예방재단2, 호서대학교 간호학과 ‧ 기초과학연구소3\n\nFactors Associated with Senile Macular Degeneration in Elders within \n\nCommunities\n\nKim, Chul-Gyu1 · Park, Yungeong2 · Park, Seungmi3\n\n1Department of Nursing, Cheongju University, Cheongju\n2Korean Foundation for the Prevention of Blindness, Seoul\n\n3Department of Nursing‧ Research Institute for Basic Sciences, Hoseo University, Asan, Korea\n\nPurpose: This study was conducted to examine the degree of senile macular degeneration in elders aged 65 or \nolder and identify factors associated with senile macular degeneration in elders within communities. Methods: \nParticipants in this cross-sectional descriptive study were 388 elders without cataract, glaucoma, and diabetic \nretinopathy. Data were collected through face to fac

In [31]:
!pip install pdfplumber

     |████████████████████████████████| 51kB 4.6MB/s 
     |████████████████████████████████| 5.6MB 12.5MB/s 
     |████████████████████████████████| 143kB 48.9MB/s 
  Created wheel for pdfplumber: filename=pdfplumber-0.5.28-cp37-none-any.whl size=32241 sha256=43b46f177976a8dcf2ab9736ceb067da0cb7150e1ef06d7473f12a9b521afa96
  Stored in directory: /root/.cache/pip/wheels/5a/9b/3d/37e37d93650be964fdd2a9babf174214fec8a0f4d222d474ab
Successfully built pdfplumber


In [32]:
import pdfplumber

text = ''
with pdfplumber.open('/content/drive/MyDrive/dataset/sample_papers.pdf') as pdf:
  for page in pdf.pages:
    text += page.extract_text()
text

"지역사회간호학회지 제24권 제1호, 2013년 3월 ISSN 1225-9594\nJ Korean Acad Community Health Nurs Vol. 24 No. 1, 1-10, March 2013 http://dx.doi.org/10.12799/jkachn.2013.24.1.1\n지역사회거주 노인의 황반변성 관련 요인\n김철규1·박윤경2·박승미3\n‧\n청주대학교 간호학과1, 한국실명예방재단2, 호서대학교 간호학과 기초과학연구소3\nFactors Associated with Senile Macular Degeneration in Elders within \nCommunities\nKim, Chul-Gyu1 · Park, Yungeong2 · Park, Seungmi3\n1Department of Nursing, Cheongju University, Cheongju\n2Korean‧ Foundation for the Prevention of Blindness, Seoul\n3Department of Nursing Research Institute for Basic Sciences, Hoseo University, Asan, Korea\nPurpose: This study was conducted to examine the degree of senile macular degeneration in elders aged 65 or \nolder and identify factors associated with senile macular degeneration in elders within communities. Methods: \nParticipants in this cross-sectional descriptive study were 388 elders without cataract, glaucoma, and diabetic \nretinopathy. Data were collected through face to face interviews using a 

## keras로 RNN 구현하기

https://wikidocs.net/22886

In [34]:
from keras.models import Sequential
from keras.layers import SimpleRNN

In [37]:
model = Sequential()
model.add(SimpleRNN(3, input_shape= (2,10))) # 히든 사이즈가 3 , input length 2 , dimession 10
model.summary()
## 출력결과 None의 의미 - 현단계에서는 batch size를 알수없음을 의미

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [38]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape = (8, 2, 10))) # 8 batch size 지정함

In [39]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_2 (SimpleRNN)     (8, 3)                    42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [56]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10), return_sequences=True))

In [57]:
model.summary() # Output Shape (batch size, input_length, hidden_size)

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_11 (SimpleRNN)    (8, 2, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


## 파이썬으로 RNN 구현하기

$$ h_t = tanh(W_x X_t + W_h H_{t-1} + b)$$

```
의사코드
hidden_State_t = 0
for input_t in input_length: #각 시점마다 입력을 받는다.
    output_t = tanh(input_t, hidden_stat_t) #각 시점에 대해서 입력과 은닉 상태를 가지고 연산
    hidden_stat_t = output_t # 계산결과는 현재 시점의 은닉 상태가 된다.
```

In [44]:
import numpy as np
timesteps = 10 # 시점의 수
input_dim = 4 # 입력 차원
hidden_size = 8 # 은닉 상태의 크기(메모리 셀의 용량?)

inputs = np.random.random((timesteps, input_dim))

hidden_state_t = np.zeros((hidden_size,)) # 초기 은닉 상태는 0(벡터)을 초기화
# 은닉 상태의 크기 hidden size로 은닉 상태로 만듬

In [61]:
inputs

array([[0.23619529, 0.31935255, 0.16086176, 0.75877665],
       [0.65997201, 0.95044914, 0.95645032, 0.47490973],
       [0.12234692, 0.94419605, 0.62469945, 0.68424246],
       [0.65463381, 0.6958246 , 0.02825208, 0.81077942],
       [0.99186555, 0.52772106, 0.45947505, 0.86258175],
       [0.74311188, 0.97503447, 0.83044387, 0.85816658],
       [0.7711558 , 0.54476491, 0.24368152, 0.64951033],
       [0.20606755, 0.17421928, 0.14792742, 0.3980554 ],
       [0.86292373, 0.83904485, 0.44528403, 0.34594288],
       [0.92405449, 0.95722069, 0.83558814, 0.2571011 ]])

In [45]:
print(hidden_state_t)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [46]:
Wx = np.random.random((hidden_size, input_dim)) # (8,4) 입력에 대한 가중치
Wh = np.random.random((hidden_size, hidden_size)) # (8, 8) 은닉상태에 대한 가중치 
b = np.random.random((hidden_size,)) # (8,) 편향

In [47]:
print(np.shape(Wx)) # 은닉상태의 크기 * 입력의 차원
print(np.shape(Wh)) # 은닉상태의 크기 * 은닉상태의크기
print(np.shape(b)) # 은닉 상태의 크기

(8, 4)
(8, 8)
(8,)


In [70]:
total_hidden_state = []

# 메모리 셀 동작
for input_t in inputs:
  output_t = np.tanh(np.dot(Wx, input_t) + np.dot(Wh, hidden_state_t) + b)
  total_hidden_state.append(list(output_t))
  print(np.shape(total_hidden_state)) # 각 시점 t별 메모리 셀의 출력의 크기는 (timestep, output_dim)

total_hidden_state = np.stack(total_hidden_state, axis = 0) #axis 0 아래로 행으로 쌓다
print(total_hidden_state) # (timestaps, outputdim) 크기

np.shape(total_hidden_state)

(1, 8)
(2, 8)
(3, 8)
(4, 8)
(5, 8)
(6, 8)
(7, 8)
(8, 8)
(9, 8)
(10, 8)
[[0.80033586 0.75993956 0.85856172 0.77154021 0.77115029 0.95136705
  0.79925857 0.84268943]
 [0.96587281 0.81546466 0.93079273 0.8765966  0.97976609 0.97957417
  0.9600776  0.98741276]
 [0.94257615 0.78360941 0.88401831 0.84153574 0.92913063 0.97017727
  0.93539419 0.95979369]
 [0.87404666 0.86215285 0.90876774 0.80170291 0.90492026 0.97952901
  0.8126668  0.93379348]
 [0.92465489 0.9037845  0.95832254 0.89460747 0.96358234 0.98636713
  0.91463045 0.97056491]
 [0.97059907 0.90590809 0.96145987 0.92353559 0.98194548 0.98941077
  0.96688187 0.98746418]
 [0.87852412 0.83327257 0.91219862 0.80475889 0.92590736 0.97500588
  0.83966573 0.9469271 ]
 [0.702305   0.56548026 0.7483488  0.61665923 0.68236753 0.90216069
  0.68712895 0.79164751]
 [0.9229289  0.78590503 0.89519542 0.76941031 0.96248122 0.97469239
  0.87432979 0.97602679]
 [0.95869338 0.78857582 0.91906691 0.82800352 0.98285249 0.97832926
  0.93879315 0.98925292]

(10, 8)

## 양방향 순환 신경망(Bidirectional Recurrent Neural Network)

In [73]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Bidirectional

model = Sequential()
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences=True), input_shape=(timesteps, input_dim)))

In [74]:
model.summary() # 16인걸 확인

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_1 (Bidirection (None, 10, 16)            208       
Total params: 208
Trainable params: 208
Non-trainable params: 0
_________________________________________________________________


In [76]:
model = Sequential()
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences = True), input_shape=(timesteps, input_dim)))
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences=True)))
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences=True)))
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences=True)))

In [77]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_2 (Bidirection (None, 10, 16)            208       
_________________________________________________________________
bidirectional_3 (Bidirection (None, 10, 16)            400       
_________________________________________________________________
bidirectional_4 (Bidirection (None, 10, 16)            400       
_________________________________________________________________
bidirectional_5 (Bidirection (None, 10, 16)            400       
Total params: 1,408
Trainable params: 1,408
Non-trainable params: 0
_________________________________________________________________


``` 
Quiz
1. Embedding을 사용하여 단어 집합(Vocabulary)의 크기가 5,000이고, 임베딩 벡터의 차원은 100입니다.
2. 은닉층에서 Simple RNN을 사용하여 은닉상태의 크기는 128이다.
3. 훈련에 사용하는 모든 샘플의 길이는 30으로 가정
4. 이진 분류를 수행하는 모델로, 출력층의 뉴련은 1개로 시그모이드 함수를 사용
5. 은닉층은 1개
총 파라미터 갯수를 구하시오.
```

In [ ]:
# parameter = w값 + bias 갯수

# Embedding = 5,000(input) * 100(embedding) = 500,000
# Wx = 100(embedding) * 128(hidden) = 12,800
# Wh = 128 * 128 = 16,384
# bias(hidden)  = 128
# Wy = 128
# bias(output) = 1

# total = 529,441

In [79]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Embedding, Dense

vocab_size = 5000
embedding_dim = 100
hidden_size = 128

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_size))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 100)         500000    
_________________________________________________________________
simple_rnn_12 (SimpleRNN)    (None, 128)               29312     
_________________________________________________________________
dense (Dense)                (None, 1)                 129       
Total params: 529,441
Trainable params: 529,441
Non-trainable params: 0
_________________________________________________________________


## 임의의 입력으로 SimpleRNN과 LSTM이해하기

hidden state : model을 설계하다보면 첫번째 은닉층을 가져다 쓸경우도 있고, 두번째 state를 가져다 쓸수도 있고 마지막 층을 가져다 쓸경우도 있는데, 안에 state결과값을 보면 좀더 쉽게 이해가 되서 보고 있습니다!

정확히는 이제 뒤에 배울 attention개념이 들어가면 이 hidden state를 가지고 점수를 매기기 때문에 return sequence를 True/False에 따라 hidden state가 어떻게 출력되는지 보시면 좋을 것 같습니다

그럼 hidden state 값을 보면서 알맞은 은닉층을 선택해서 사용할 수 있다는 말씀으로 이해하면 되겠네요



In [81]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [95]:
train_x = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_x)) # 단어 벡터차원은 5, 문장의 길이가 4인경우를 가정

(4, 5)


In [96]:
train_x = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_x = np.array(train_x, dtype=np.float32)
print(train_x.shape) # (batch_size, timesteps, input_dim) batch_size - 한번에 학습할수 있는 데이터의 양

(1, 4, 5)


In [99]:
rnn = SimpleRNN(3) # rnn = SimpleRNN(3, return_sequences = False, return_stagte = False)와 동일
hidden_state = rnn(train_x)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state : [[ 0.33651322 -0.62757623  0.1544512 ]], shape: (1, 3)


In [100]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_state = rnn(train_x)
print('hidden states : {}, shape : {}'.format(hidden_state, hidden_state.shape)) 

hidden states : [[[0.35773936 0.99995714 0.56691444]
  [0.7606846  0.99506265 0.05763947]
  [0.93739444 0.9895649  0.4497334 ]
  [0.95817757 0.8271103  0.69776803]]], shape : (1, 4, 3)


In [101]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_state, last_state = rnn(train_x)

print('hidden states: {}, shape : {}'.format(hidden_state, hidden_state.shape))
print('last hidden states: {}, shape : {}'.format(last_state, last_state.shape))

hidden states: [[[ 0.99979925 -0.9981098  -0.9783002 ]
  [ 0.6674162  -0.99938804 -0.98712254]
  [-0.40546098 -0.99510545 -0.35774785]
  [-0.50536835 -0.22089484 -0.9205884 ]]], shape : (1, 4, 3)
last hidden states: [[-0.50536835 -0.22089484 -0.9205884 ]], shape : (1, 3)


In [102]:
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_x)

print('hidden state : {}, shape : {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape : {}'.format(last_state, last_state.shape))

hidden state : [[ 0.98252606 -0.9389156   0.59284484]], shape : (1, 3)
last hidden state : [[ 0.98252606 -0.9389156   0.59284484]], shape : (1, 3)


## LSTM 이해하기

In [103]:
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_x)

print('hidden state : {}, shape :{}'.format(hidden_state, hidden_state.shape))
print('last hidden state: {}, shape : {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape : {}'.format(last_cell_state, last_cell_state.shape))

hidden state : [[-0.18220362  0.3251987   0.13099739]], shape :(1, 3)
last hidden state: [[-0.18220362  0.3251987   0.13099739]], shape : (1, 3)
last cell state : [[-0.925191    0.4423955   0.15847361]], shape : (1, 3)


In [104]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_state, last_hidden_state, last_cell_state = lstm(train_x)

print('hidden state : {}, shape : {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape : {}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape : {}'.format(last_cell_state, last_cell_state.shape))

hidden state : [[[-0.0217876  -0.23129399 -0.03052996]
  [-0.01117585 -0.354371   -0.06583661]
  [-0.08656603 -0.4620223  -0.21836679]
  [-0.08321761 -0.21928605 -0.20938842]]], shape : (1, 4, 3)
last hidden state : [[-0.08321761 -0.21928605 -0.20938842]], shape : (1, 3)
last cell state : [[-0.7908035 -2.064783  -1.053983 ]], shape : (1, 3)


## Bidirectional (LSTM)이해하기

In [105]:
k_init = tf.keras.initializers.Constant(value = 0.1)
b_init = tf.keras.initializers.Constant(value = 0)
r_init = tf.keras.initializers.Constant(value = 0.1)

In [109]:
bilstm = Bidirectional(LSTM(3, return_sequences=False, return_state=True, kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_x)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[0.63031393 0.63031393 0.63031393 0.7038734  0.7038734  0.7038734 ]], shape: (1, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


In [110]:
bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True, kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_x)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape)) # 모든 시점의 hidden state가 출력
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape)) # 뒤에서 2번째
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape)) # 앞에서 2번째

hidden states : [[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.5511133  0.5511133  0.5511133  0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.63031393 0.63031393 0.63031393 0.21942244 0.21942244 0.21942244]]], shape: (1, 4, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


## RNN을 이용한 텍스트 생성(Text Generation)
- 다 대 일 (many to one)구조의 RNN을 사용하여 문맥을 반영해서 텍스트를 생성하는 모델을 만들어 보자
- '경마장에 있는 말이 뛰고 있다'
- '그의 말이 법이다'
- '가는 말이 고와야 오는 말이 곱다'

In [112]:
import pandas as pd
# 위 3문장을 재구성하면, 아래와 같이 총 11개의 샘플이 구성됨
content = [['경마장에', '있는'],['경마장에 있는','말이'],['경마장에 있는 말이', '뛰고'],['경마장에 있는 말이 뛰고','있다'],['그의','말이'],['그의 말이','법이다'],['가는', '말이'],['가는 말이','고와야'],['가는 말이 고와야','오는'],['가는 말이 고와야 오는','말이'],['가는 말이 고와야 오는 말이','곱다']]
df = pd.DataFrame(content)
df.index = ['1', '2', '3', '4', '5', '6', '7', '8', '9','10','11']
df.columns = ['X', 'y']
df

X    y
1              경마장에   있는
2           경마장에 있는   말이
3        경마장에 있는 말이   뛰고
4     경마장에 있는 말이 뛰고   있다
5                그의   말이
6             그의 말이  법이다
7                가는   말이
8             가는 말이  고와야
9         가는 말이 고와야   오는
10     가는 말이 고와야 오는   말이
11  가는 말이 고와야 오는 말이   곱다

### 데이터에 대한 이해와 전처리

In [113]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [114]:
text = """ 경마장에 있는 말이 뛰고 있다 \n
그의 말이 법이다.\n
가는 말이 고와야 오는 말이 곱다\n"""

In [122]:
# 단어집합 생성 및 크기 확인
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index)+1 

# 케라스 토크나이저 점수 인코딩은 인덱스가 1부터 시작
# 케라스 원-핫 인코딩에서 배열의 인덱스 0부터 시작하기 때문에
# 배열의 크기를 실제 단어 집합의 크기보다 +1로 생성해야함 그래서 미리 +1 선언
print('단어 집합의 크기 : %d'% vocab_size)

단어 집합의 크기 : 12


In [123]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [138]:
# 훈련데이터 만들기
sequences = list()

for line in text.split('\n'):
  encoded = t.texts_to_sequences([line])[0]
  for i in range(1, len(encoded)):
    sequence = encoded[: i+1]
    sequences.append(sequence)

print('학습에 사용할 샘플의 갯수 : %d' % len(sequences))

학습에 사용할 샘플의 갯수 : 11


In [139]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [140]:
max_len = max(len(l) for l in sequences) # 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 6


In [141]:
## 패딩 - 가장 길이가 큰것을 기준으로 0으로 채워주기
sequences = pad_sequences(sequences, maxlen = max_len, padding='pre') # 앞에

In [142]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [143]:
sequences = np.array(sequences)
x = sequences[:, :-1]
y = sequences[:, -1]
# 리스트의 마지막 값을 제외하고 지정한 것은 x
# 리스트의 마지막 값만 지정한 것은 y -> 레이블에 해당

In [144]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [145]:
y = to_categorical(y, num_classes=vocab_size) # one-hot

In [146]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## 모델 설계하기

In [147]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [152]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 1s - loss: 2.5171 - accuracy: 0.0000e+00
Epoch 2/200
1/1 - 0s - loss: 2.5034 - accuracy: 0.0000e+00
Epoch 3/200
1/1 - 0s - loss: 2.4902 - accuracy: 0.0909
Epoch 4/200
1/1 - 0s - loss: 2.4774 - accuracy: 0.0909
Epoch 5/200
1/1 - 0s - loss: 2.4647 - accuracy: 0.0909
Epoch 6/200
1/1 - 0s - loss: 2.4520 - accuracy: 0.1818
Epoch 7/200
1/1 - 0s - loss: 2.4391 - accuracy: 0.2727
Epoch 8/200
1/1 - 0s - loss: 2.4260 - accuracy: 0.3636
Epoch 9/200
1/1 - 0s - loss: 2.4125 - accuracy: 0.3636
Epoch 10/200
1/1 - 0s - loss: 2.3984 - accuracy: 0.3636
Epoch 11/200
1/1 - 0s - loss: 2.3836 - accuracy: 0.3636
Epoch 12/200
1/1 - 0s - loss: 2.3681 - accuracy: 0.3636
Epoch 13/200
1/1 - 0s - loss: 2.3517 - accuracy: 0.3636
Epoch 14/200
1/1 - 0s - loss: 2.3343 - accuracy: 0.3636
Epoch 15/200
1/1 - 0s - loss: 2.3159 - accuracy: 0.3636
Epoch 16/200
1/1 - 0s - loss: 2.2963 - accuracy: 0.3636
Epoch 17/200
1/1 - 0s - loss: 2.2755 - accuracy: 0.3636
Epoch 18/200
1/1 - 0s - loss: 2.2535 - accuracy: 

In [158]:
# 문장을 생성하는 함수 만들어서 출력하기
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=5, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [160]:
print(sentence_generation(model, t, '경마장에', 4)) # 뒤에 4개 예측

경마장에 있는 말이 뛰고 있다


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [161]:
print(sentence_generation(model, t, '그의', 2)) # 뒤에 2개 예측

그의 말이 법이다


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [171]:
print(sentence_generation(model, t, '가는', 5)) # 뒤에 5개 예측

가는 말이 고와야 오는 말이 곱다


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


#LSTM을 이용한 텍스트 생성

In [175]:
import pandas as pd
from string import punctuation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [176]:
df = pd.read_csv('/content/drive/MyDrive/dataset/ArticlesApril2018.csv')

In [178]:
print('열의 갯수 :', len(df.columns))
print(df.columns)

열의 갯수 : 15
Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [195]:
# Null이 있는지 확인
print(df['headline'].isnull().sum())

df['headline'].isnull().values.any()

0


False

In [192]:
# headline 열에서 모든 신문 기사의 제목을 뽑아서 하나의 리스트로 저장하자
df.head(3)
headline = []

for i in df['headline']:
  headline.append(i)

type(headline)

# headline.extend(list(df.headline.values)) # 강사님 방법

list

In [193]:
# 상위 5개만 출력
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [196]:
# 총 샘플의 갯수
print('총 샘플의 갯수 : {}'.format(len(headline)))

총 샘플의 갯수 : 1324


In [207]:
df['headline'].value_counts()

Unknown                                                                   110
Variety: Acrostic                                                           3
Why Teenagers Become ‘Allergic’ to Their Parents                            1
It’s O.K. to Play in the Street                                             1
E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.      1
                                                                         ... 
The Art of the Beef Stew                                                    1
Horror of Being Governed by 'Fox &amp; Friends'                             1
The Failures of Anti-Trumpism                                               1
After Hurricane’s Ruin, the Return to Puerto Rico                           1
Gun Makers Must Do More                                                     1
Name: headline, Length: 1213, dtype: int64

In [209]:
# unknown값을 가진 샘플 제거
# 제거 후 샘플의 개수 출력
headline = [n for n in headline if n != "Unknown"]

print('총 샘플의 갯수 : {}'.format(len(headline)))

총 샘플의 갯수 : 1214


In [212]:
def repreprocessing(s):
  s = s.encode("utf8").decode("ascii", 'ignore')
  return ''.join(c for c in s if c not in punctuation).lower() # 구두점제거와 동시에 소문자화,  punctuation -> . 을 의미

text = [repreprocessing(x) for x in headline]
text[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [213]:
t = Tokenizer()
t.fit_on_texts(text)
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 3494


In [214]:
sequences = list()

In [218]:
for line in text:
  encoded = t.texts_to_sequences([line])[0] #각 샘플에 대한 정수 인코딩
  for i in range(1, len(encoded)):
    sequence = encoded[:i+1]
    sequences.append(sequence)

sequences[:11]

[[99, 269],
 [99, 269, 371],
 [99, 269, 371, 1115],
 [99, 269, 371, 1115, 582],
 [99, 269, 371, 1115, 582, 52],
 [99, 269, 371, 1115, 582, 52, 7],
 [99, 269, 371, 1115, 582, 52, 7, 2],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10, 1116],
 [100, 3]]

In [221]:
index_to_word = {}

for key, value in t.word_index.items():
  index_to_word[value] = key

print('빈도수 상위 582번 단어 : {}'.format(index_to_word[582]))

빈도수 상위 582번 단어 : offer


In [224]:
max_len = max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 24


In [225]:
sequences  = pad_sequences(sequences, maxlen = max_len, padding = 'pre')
print(sequences[:3])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0   99  269]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0   99  269  371]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0   99  269  371 1115]]


In [226]:
sequenece = np.array(sequences)
x = sequences[:, :-1]
y = sequences[:, -1]

In [227]:
print(x[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0  99]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0  99 269]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0  99 269 371]]


In [228]:
print(y[:3])

[ 269  371 1115]


In [229]:
y = to_categorical(y, num_classes=vocab_size)

In [230]:
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### 모델 설계

In [231]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [236]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length = max_len - 1)) # 파라미터 수 = vocab_size * 10 
model.add(LSTM(128)) # 은닉 상태 크기 - 보통 2의 배수로 많이 쓴다, 128, 256, 512, 1024 등등
model.add(Dense(vocab_size, activation = 'softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x , y , epochs=200, verbose=2) # verbose 0 = silent, 1 = progress bar,2 = one line per epoch

Epoch 1/200
732/732 - 22s - loss: 7.2843 - accuracy: 0.0298
Epoch 2/200
732/732 - 20s - loss: 6.7175 - accuracy: 0.0439
Epoch 3/200
732/732 - 20s - loss: 6.2097 - accuracy: 0.0545
Epoch 4/200
732/732 - 20s - loss: 5.6629 - accuracy: 0.0692
Epoch 5/200
732/732 - 20s - loss: 5.1841 - accuracy: 0.0854
Epoch 6/200
732/732 - 20s - loss: 4.7658 - accuracy: 0.1153
Epoch 7/200
732/732 - 20s - loss: 4.3826 - accuracy: 0.1521
Epoch 8/200
732/732 - 20s - loss: 4.0325 - accuracy: 0.2004
Epoch 9/200
732/732 - 20s - loss: 3.7159 - accuracy: 0.2558
Epoch 10/200
732/732 - 20s - loss: 3.4330 - accuracy: 0.3051
Epoch 11/200
732/732 - 20s - loss: 3.1733 - accuracy: 0.3514
Epoch 12/200
732/732 - 20s - loss: 2.9441 - accuracy: 0.3957
Epoch 13/200
732/732 - 20s - loss: 2.7368 - accuracy: 0.4363
Epoch 14/200
732/732 - 20s - loss: 2.5453 - accuracy: 0.4749
Epoch 15/200
732/732 - 20s - loss: 2.3728 - accuracy: 0.5084
Epoch 16/200
732/732 - 20s - loss: 2.2154 - accuracy: 0.5406
Epoch 17/200
732/732 - 20s - loss

In [ ]:
# 문장을 생성하는 함수 만들어서 출력하기
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=23, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [237]:
print(sentence_generation(model, t, 'i', 10))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


i jersey turk to not feels accept you client weapons turk


In [238]:
print(sentence_generation(model, t, 'how', 10))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


how are known for known city known of next war us


In [239]:
print(sentence_generation(model, t, 'former', 10))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


former epas you attitudes virtual our known and known for trump
