In [1]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
import numpy as np
import pandas as pd

In [9]:
arr = np.array([1, 2, 3, 4, 5], dtype = float) # 타입을 float

In [12]:
arr.dtype
arr

array([1., 2., 3., 4., 5.])

In [11]:
arr.astype(int) # 타입 변경

array([1, 2, 3, 4, 5])

In [13]:
np.zeros(10, dtype = int) # 0으로 만들기

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.linspace(0, 1, 5) # 5 등분

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# 0 ~ 9 까지, 3행 4열로 랜덤
# randint - random int
x2 = np.random.randint(10, size = (3, 4)) 

In [19]:
x2

array([[3, 3, 5, 8],
       [3, 0, 1, 4],
       [9, 8, 5, 3]])

In [20]:
x2.ndim # number of dimession

2

In [22]:
x2.shape

(3, 4)

In [23]:
x2.size # 3 * 4

12

In [24]:
x2.dtype

dtype('int32')

In [25]:
x = np.arange(7)

In [26]:
x[3] = 10 # 리스트 내 값 변경
x

array([ 0,  1,  2, 10,  4,  5,  6])

In [27]:
x[1:4]

array([ 1,  2, 10])

In [28]:
x[2:]

array([ 2, 10,  4,  5,  6])

In [29]:
x[:4]

array([ 0,  1,  2, 10])

In [31]:
x

array([ 0,  1,  2, 10,  4,  5,  6])

In [30]:
x[::2] # 2칸씩 가져오겠다

array([0, 2, 4, 6])

In [34]:
x = np.arange(8)

In [35]:
x.shape # 1차원 1 생략

(8,)

In [37]:
x.reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
x.reshape((2, -1)) # -1 은 알아서 끝자리 맞춰줌

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [39]:
# 이어 붙이고 나누고
x = np.array([0, 1, 2])
y = np.array([3, 4, 5])
np.concatenate([x, y])

array([0, 1, 2, 3, 4, 5])

In [42]:
matrix =  np.arange(4).reshape(2, 2)
np.concatenate([matrix, matrix], axis = 0) # 0 행기준

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [44]:
np.concatenate([matrix, matrix], axis = 1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [57]:
matrix =  np.arange(16).reshape(4, 4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
upper, lower = np.split(matrix, [3], axis = 0)
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
lower

array([[12, 13, 14, 15]])

In [66]:
x = np.arange(8).reshape((2, 4))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
np.sum(x)

28

In [62]:
np.min(x)

0

In [63]:
np.max(x)

7

In [64]:
np.mean(x)

3.5

In [65]:
np.sum(x, axis = 0)

array([ 4,  6,  8, 10])

In [67]:
np.sum(x, axis = 1)

array([ 6, 22])