In [1]:
import numpy as np

In [2]:
a = [10, 20, 30, 40, 50]

In [3]:
a

[10, 20, 30, 40, 50]

In [4]:
type(a)

list

In [5]:
b = np.array(a)

In [6]:
b

array([10, 20, 30, 40, 50])

In [7]:
type(b)

numpy.ndarray

In [8]:
print(b)

[10 20 30 40 50]


In [11]:
b.shape

(5,)

In [12]:
c = np.array([5, 4, 3, 2, 1])

In [13]:
c

array([5, 4, 3, 2, 1])

In [14]:
b + c

array([15, 24, 33, 42, 51])

In [15]:
b + 5

array([15, 25, 35, 45, 55])

In [16]:
a + 5 # list에서는 불가능

TypeError: can only concatenate list (not "int") to list

In [17]:
a + [5, 4, 3, 2, 1] # list에서는 + 이어붙이기가 된다.

[10, 20, 30, 40, 50, 5, 4, 3, 2, 1]