In [1]:
import numpy as np

In [2]:
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [3]:
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [4]:
a.shape

(2, 4)

In [5]:
b, c = a.shape

In [6]:
b

2

In [7]:
c

4

In [8]:
a[0, 0]

10

In [9]:
a[-1, -1]

80

In [10]:
a[1, 1:]

array([60, 70, 80])

In [11]:
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [12]:
a[0, 1] = 2

In [13]:
a

array([[10,  2, 30, 40],
       [50, 60, 70, 80]])

In [17]:
b = np.zeros((2, 4))

In [18]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
c = np.ones((3, 5))

In [20]:
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
c = np.arange(8)

In [22]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
c.reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
c = c.reshape(2, 4)

In [26]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
c = c.reshape(4, 2)

In [28]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [29]:
c.sum()

28

In [30]:
d = c.copy()

In [31]:
d[0, 0] = 10

In [32]:
d

array([[10,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

In [33]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [34]:
d == c

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [35]:
e = np.arange(49).reshape(7, 7)

In [36]:
e

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [37]:
e[:, 1:3]

array([[ 1,  2],
       [ 8,  9],
       [15, 16],
       [22, 23],
       [29, 30],
       [36, 37],
       [43, 44]])

In [38]:
e[3:, :4]

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [39]:
e[3:, :4].sum()

528

In [42]:
f = e[3:, :4].copy()

In [43]:
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [44]:
e[4, 0 ] = 100

In [45]:
e

array([[  0,   1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12,  13],
       [ 14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27],
       [100,  29,  30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47,  48]])

In [46]:
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [47]:
f.sum()

528