In [3]:
import numpy as np

In [4]:
a = [10, 20, 30, 40, 50]
b = np.array(a)

In [5]:
np.sum(b)

150

In [6]:
np.mean(b)

30.0

In [7]:
np.max(b)

50

In [8]:
np.min(b)

10

In [9]:
c = b / 3

In [10]:
c

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [11]:
np.round(c, 1)

array([ 3.3,  6.7, 10. , 13.3, 16.7])

In [12]:
np.round(c, 3)

array([ 3.333,  6.667, 10.   , 13.333, 16.667])

In [14]:
np.round(c, 0)

array([ 3.,  7., 10., 13., 17.])

In [15]:
b[0]

10

In [16]:
b[-1]

50

In [17]:
b[1:3]

array([20, 30])

In [18]:
b[2:]

array([30, 40, 50])

In [19]:
np.sum(b[2:])

120

In [20]:
np.mean(b[2:])

40.0

In [21]:
b[1] = 200

In [22]:
b

array([ 10, 200,  30,  40,  50])

In [23]:
d = np.arange(5)

In [24]:
d

array([0, 1, 2, 3, 4])

In [25]:
e = np.arange(3, 8)

In [26]:
e

array([3, 4, 5, 6, 7])

In [27]:
f = np.arange(3, 8, 2)

In [28]:
f

array([3, 5, 7])

In [29]:
g = np.zeros(5)

In [30]:
g

array([0., 0., 0., 0., 0.])

In [31]:
h = np.ones(5)

In [32]:
h

array([1., 1., 1., 1., 1.])

In [33]:
b

array([ 10, 200,  30,  40,  50])

In [34]:
bb = b

In [35]:
bb

array([ 10, 200,  30,  40,  50])

In [36]:
bb[0] = 100

In [37]:
bb

array([100, 200,  30,  40,  50])

In [38]:
b

array([100, 200,  30,  40,  50])

In [40]:
b == bb # 하나만 바꿔도 연계됨

array([ True,  True,  True,  True,  True])

In [41]:
bb = b.copy() # Tip

In [42]:
bb

array([100, 200,  30,  40,  50])

In [44]:
b[2] = 300

In [45]:
b

array([100, 200, 300,  40,  50])

In [46]:
bb

array([100, 200,  30,  40,  50])

In [47]:
b == bb # 다르다

array([ True,  True, False,  True,  True])