In [1]:
import numpy as np

In [2]:
a = np.arange(5, 45, 5).reshape(2, 4)

In [4]:
b = np.arange(20, 36, 2).reshape(2, 4)

In [5]:
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [6]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [7]:
a + b

array([[25, 32, 39, 46],
       [53, 60, 67, 74]])

In [8]:
a - b

array([[-15, -12,  -9,  -6],
       [ -3,   0,   3,   6]])

In [9]:
b - a

array([[15, 12,  9,  6],
       [ 3,  0, -3, -6]])

In [10]:
a * b # 행렬이지만 행렬 곱이 아니다

array([[ 100,  220,  360,  520],
       [ 700,  900, 1120, 1360]])

In [11]:
a / b

array([[0.25      , 0.45454545, 0.625     , 0.76923077],
       [0.89285714, 1.        , 1.09375   , 1.17647059]])

In [12]:
a % b

array([[ 5, 10, 15, 20],
       [25,  0,  3,  6]], dtype=int32)

In [13]:
a // b

array([[0, 0, 0, 0],
       [0, 1, 1, 1]], dtype=int32)

In [14]:
a * 10

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [15]:
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [16]:
c = a * 10

In [17]:
c

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [18]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [20]:
bb = b.reshape(4, 2)

In [21]:
bb

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34]])

In [22]:
a @ bb # 행렬 곱

array([[1400, 1500],
       [3480, 3740]])