In [1]:
import pandas as pd

In [3]:
a = {'a' : 10, 'b' : 20, 'c': 30, 'd': 40, 'e' : 50}

In [4]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [5]:
type(a)

dict

In [6]:
b = pd.Series(a)

In [7]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [8]:
type(b)

pandas.core.series.Series

In [9]:
b.shape

(5,)

In [10]:
import numpy as np

In [11]:
aa = np.arange(3, 10)

In [12]:
aa

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
bb = pd.Series(aa)

In [14]:
bb

0    3
1    4
2    5
3    6
4    7
5    8
6    9
dtype: int32

In [16]:
type(bb)

pandas.core.series.Series

In [17]:
bb.shape

(7,)

In [18]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [19]:
a.keys()

dict_keys(['a', 'b', 'c', 'd', 'e'])

In [21]:
a.values()

dict_values([10, 20, 30, 40, 50])

In [22]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [24]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [25]:
b.values

array([10, 20, 30, 40, 50], dtype=int64)

In [26]:
c = [10, 20, 30, 40, 50]

In [28]:
d = pd.Series(c)

In [29]:
d

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [30]:
type(d)

pandas.core.series.Series

In [31]:
d.shape

(5,)

In [32]:
d.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
d.values

array([10, 20, 30, 40, 50], dtype=int64)

In [34]:
e = ['a', 'b', 'c', 'd', 'e']

In [35]:
f = [10, 20, 30, 40, 50]

In [36]:
g = pd.Series(f, index = e)

In [37]:
g

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [38]:
g['a']

10

In [39]:
g['a' : 'd'] # 숫자랑 다름 d 포함

a    10
b    20
c    30
d    40
dtype: int64

In [40]:
g[0 : 4]

a    10
b    20
c    30
d    40
dtype: int64