## 기초4_문제

In [117]:
import pandas as pd
import numpy as np

In [118]:
'''
seaborn의 타이타닉 데이터를 불러오자
'''

import seaborn as sns
df = sns.load_dataset('titanic')

In [119]:
'''
실습을 위에 데이터 소실 만들기
변경 없이 실행 시켜주시면 됩니다.
'''
df.loc[1, 'pclass'] = '?'

In [79]:
'''
데이터구조 확인 (기계적으로 확인하자)
'''


'\n데이터구조 확인 (기계적으로 확인하자)\n'

In [120]:
df.shape

(891, 15)

In [121]:
df.head()

survived pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0      3    male  22.0      1      0   7.2500        S  Third   
1         1      ?  female  38.0      1      0  71.2833        C  First   
2         1      3  female  26.0      0      0   7.9250        S  Third   
3         1      1  female  35.0      1      0  53.1000        S  First   
4         0      3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [122]:
df.info() # pclass 가 숫자랑 문자  혼합... 이상 확인필요

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    object  
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(3), object(6)
memory usage: 80.6+ KB


In [123]:
df.describe(include = "all")

survived  pclass   sex         age       sibsp       parch  \
count   891.000000   891.0   891  714.000000  891.000000  891.000000   
unique         NaN     4.0     2         NaN         NaN         NaN   
top            NaN     3.0  male         NaN         NaN         NaN   
freq           NaN   491.0   577         NaN         NaN         NaN   
mean      0.383838     NaN   NaN   29.699118    0.523008    0.381594   
std       0.486592     NaN   NaN   14.526497    1.102743    0.806057   
min       0.000000     NaN   NaN    0.420000    0.000000    0.000000   
25%       0.000000     NaN   NaN   20.125000    0.000000    0.000000   
50%       0.000000     NaN   NaN   28.000000    0.000000    0.000000   
75%       1.000000     NaN   NaN   38.000000    1.000000    0.000000   
max       1.000000     NaN   NaN   80.000000    8.000000    6.000000   

              fare embarked  class  who adult_male deck  embark_town alive  \
count   891.000000      889    891  891        891  203          889   891   
unique         NaN        3      3    3          2    7            3     2   
top            NaN        S  Third  man       True    C  Southampton    no   
freq           NaN      644    491  537        537   59          644   549   
mean     32.204208      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
std      49.693429      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
min       0.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
25%       7.910400      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
50%      14.454200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
75%      31.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
max     512.329200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   

       alone  
count    891  
unique     2  
top     True  
freq     537  
mean     NaN  
std      NaN  
min      NaN  
25%      NaN  
50%      NaN  
75%      NaN  
max      NaN

In [4]:
'''
pclass 열의 자료형 확인 _문자열(object)
df['열'].unique() 활용
'''


array([3, '?', 1, 2], dtype=object)

In [127]:
print(df['pclass'].dtypes) # print 안찍으면 dtype('O') 로 출력

object


In [83]:
df['pclass'].unique()

array([3, '?', 1, 2], dtype=object)

In [5]:
'''
pclass의 목록 확인
'''

3    491
1    215
2    184
?      1
Name: pclass, dtype: int64

In [128]:
df['pclass'].value_counts(dropna = False)

3    491
1    215
2    184
?      1
Name: pclass, dtype: int64

In [7]:
'''
pclass열의 누락 데이터('?') 삭제 후에 문자열을 정수형으로 변경
'''

In [131]:
df['pclass'].head()

0    3.0
1    NaN
2    3.0
3    1.0
4    3.0
Name: pclass, dtype: float64

In [132]:
df['pclass'].replace('?', np.nan, inplace = True)
print(df['pclass'].value_counts(dropna = False))
print()
df.dropna(subset = ['pclass'],inplace = True)
print(df['pclass'].value_counts(dropna = False))

3.0    491
1.0    215
2.0    184
NaN      1
Name: pclass, dtype: int64

3.0    491
1.0    215
2.0    184
Name: pclass, dtype: int64


In [133]:
df['pclass'].head()

0    3.0
2    3.0
3    1.0
4    3.0
5    3.0
Name: pclass, dtype: float64

In [135]:
df['pclass'] = df['pclass'].astype(int)

In [8]:
'''
pclass 열의 자료형 확인 _int
'''

int32


In [137]:
print(df['pclass'].dtype) 

int32


In [9]:
'''
df['열'].unique() 를 활용하여
pclass 열의 고유값 확인
'''


array([3, 1, 2])

In [138]:
df['pclass'].unique()

array([3, 1, 2])

In [10]:
'''
정수형 데이터를 문자형 데이터로 변환 
1을 1등급으로 변경
2를 2등급으로 변경
3을 3등급으로 변경
'''


array(['3등급', '1등급', '2등급'], dtype=object)

In [139]:
df1=df.copy()
print(df1['pclass'].value_counts())
print()
df['pclass'].replace({1:'1등급', 2:'2등급', 3:'3등급'}, inplace = True)
print(df['pclass'].unique())

df['pclass'].value_counts()

3    491
1    215
2    184
Name: pclass, dtype: int64

['3등급' '1등급' '2등급']


3등급    491
1등급    215
2등급    184
Name: pclass, dtype: int64

In [11]:
'''
pclass 열의 자료형 확인 _object
'''
 

object


In [140]:
print(df['pclass'].dtypes) # 문자형인 경우는 print를 사용

object


In [12]:
'''
origin 열의 문자열 자료형을 범주형으로 변환
'''


category


In [95]:
df['pclass'] = df['pclass'].astype('category')
print(df['pclass'].dtype)

category


In [13]:
'''
origin 열의 범주형을 문자열로 다시 변환
'''


object


In [96]:
df['pclass'] = df['pclass'].astype('str')
print(df['pclass'].dtype)

object


In [14]:
'''
fare열을 np.histogram 함수로 3개의 bin으로 나누는 경계 값의 리스트 구하기

'''

[870  17   3]

[  0.     170.7764 341.5528 512.3292]


In [142]:
count, bin_dividers = np.histogram(df['fare'], bins =3) # 구간을 3개로
print(count)
print()
print(bin_dividers)

[870  17   3]

[  0.     170.7764 341.5528 512.3292]


In [15]:
'''
위에서 구한 세가지의 그룹을 ['하', '중', '상']로 변경해 보자
'''


In [110]:
df['fare_bin'] = pd.cut(x=df['fare'], # 데이터 배열
                    bins = bin_dividers, # 경계값 리스트
                    labels = ['하', '중', '상'], # bin 이름
                    include_lowest =True) # 각 구간의 낮은 경계값 포함

df['fare_bin'].value_counts(dropna = False)

하    870
중     17
상      3
Name: fare_bin, dtype: int64

In [16]:
'''위의 변경값 확인'''


        fare fare_bin
881   7.8958        하
882  10.5167        하
883  10.5000        하
884   7.0500        하
885  29.1250        하
886  13.0000        하
887  30.0000        하
888  23.4500        하
889  30.0000        하
890   7.7500        하


In [112]:
print(df.loc[881:891,['fare', "fare_bin"]])

        fare fare_bin
881   7.8958        하
882  10.5167        하
883  10.5000        하
884   7.0500        하
885  29.1250        하
886  13.0000        하
887  30.0000        하
888  23.4500        하
889  30.0000        하
890   7.7500        하


In [17]:
'''
fare_bin 열의 범주형 데이터를 더미 변수로 변환
'''


    하  중  상
0   1  0  0
2   1  0  0
3   1  0  0
4   1  0  0
5   1  0  0
6   1  0  0
7   1  0  0
8   1  0  0
9   1  0  0
10  1  0  0
11  1  0  0
12  1  0  0
13  1  0  0
14  1  0  0
15  1  0  0


In [115]:
print(pd.get_dummies(df['fare_bin']).head(15)) # 더미변수

    하  중  상
0   1  0  0
2   1  0  0
3   1  0  0
4   1  0  0
5   1  0  0
6   1  0  0
7   1  0  0
8   1  0  0
9   1  0  0
10  1  0  0
11  1  0  0
12  1  0  0
13  1  0  0
14  1  0  0
15  1  0  0
