In [1]:
import pandas as pd

fish = pd.read_csv('https://bit.ly/fish_csv')
print(fish.head())

# print(type(fish))

  Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340


In [4]:
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()

fish_target = fish['Species'].to_numpy()

In [6]:
fish_target

array(['Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Whitefish',
       'Whitefish', 'Whitefish', 'Whitefish', 'Whitefish', 'Whitefish',
       'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki',
       'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perc

In [5]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    fish_input, fish_target, random_state=42)

In [26]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

#Compute the mean and std to be used for later scaling.
## scaling 안하는 경우 -> 분류가 아닌 예측의 경우, tree

ss.fit(train_input)

train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [44]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_scaled, train_target)

print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

# lr = LogisticRegression(penalty='l2', C=20, max_iter=1000) 
# lr.fit(train_scaled, train_target)

# print(lr.score(train_scaled, train_target))
# print(lr.score(test_scaled, test_target))
# LogisticRegression(
#     penalty='l2', l2 - 리지, l1-라소
#     *,
#     dual=False,
#     tol=0.0001,
#     C=1.0, # 1 / lambda 
#     fit_intercept=True,
#     intercept_scaling=1,
#     class_weight=None,
#     random_state=None,
#     solver='lbfgs',
#     max_iter=100,
#     multi_class='auto',
#     verbose=0,
#     warm_start=False,
#     n_jobs=None,
#     l1_ratio=None,
# )

0.8067226890756303
0.85


In [45]:
print(lr.predict(test_scaled[:5]))

['Perch' 'Smelt' 'Pike' 'Perch' 'Perch']


In [46]:
import numpy as np

In [47]:
proba = lr.predict_proba(test_scaled[:5])
print(np.round(proba, decimals=3))

[[0.004 0.092 0.545 0.008 0.281 0.061 0.01 ]
 [0.    0.061 0.126 0.002 0.087 0.722 0.001]
 [0.009 0.009 0.223 0.569 0.17  0.006 0.013]
 [0.061 0.077 0.526 0.036 0.257 0.003 0.04 ]
 [0.004 0.03  0.664 0.026 0.245 0.018 0.013]]


In [48]:
print(lr.coef_, lr.intercept_)

[[-1.48635407e-01 -8.16338300e-02  6.40677025e-01  2.81886254e+00
  -3.23791215e-01]
 [-3.35559709e-01 -8.21454187e-01 -8.35625183e-01  1.91834624e+00
  -8.55673174e-01]
 [ 1.30777936e+00  3.20627792e-01 -1.31830404e+00 -1.71471286e+00
   1.64054397e+00]
 [ 1.33816721e-03  1.72779398e+00  1.75766272e+00 -1.28638162e+00
  -6.35345781e-01]
 [-8.14258430e-01 -5.24809489e-01  3.53859503e-01 -4.21963234e-01
   6.26572878e-01]
 [-3.55031912e-01 -6.41091506e-01 -6.57484132e-01 -1.46560568e+00
  -1.51685481e+00]
 [ 3.44367925e-01  2.05672435e-02  5.92141133e-02  1.51454608e-01
   1.06454813e+00]] [ 0.38862776 -0.11439729  2.40795555  0.04859162  1.15910169 -3.78185807
 -0.10802126]


## lasso

In [49]:
lr = LogisticRegression(penalty = 'l1', C=20, max_iter=1000, solver='liblinear')

lr.fit(train_scaled, train_target)

print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

# ‘newton-cg’, ‘lbfgs’, ‘sag’ and ‘saga’ handle L2 or no penalty
# ‘liblinear’ and ‘saga’ also handle L1 penalty
# ‘saga’ also supports ‘elasticnet’ penalty

0.9663865546218487
0.925


In [50]:
print(lr.coef_, lr.intercept_)

[[ -7.35612412   0.           5.05871523  13.06733515   0.        ]
 [ -8.02115711  16.39537748 -29.93026455  14.7343097    0.        ]
 [ -2.43369577  73.81209548 -78.79714514   2.13597649   4.38225903]
 [  0.           0.           9.62590673  -4.61068527  -3.87766674]
 [ -9.30730354 -42.41828314  39.7947627   -5.15651097   9.42156067]
 [ -7.53579924   0.           7.73250297  -9.24411999  -5.28487516]
 [ -1.98242966  -1.45137452   0.           0.           3.71523595]] [-10.06125985 -12.79755565  -4.00677415  -6.03449221  -6.64651241
 -18.14411876  -4.60790092]


In [51]:
print(np.sum(lr.coef_ == 0))

8
